### ISSUE TITLE
How to run these example code?

### ISSUE THREAD

**Issue by frokaikan** [HexHive/FuzzGen#10]
I compile libopus on ubuntu and try drivers in example/libopus, but there seems to exist compile error on this code......
One of the compile error is:
fuzzgen.cpp:562:17: error: use of undeclared identifier 'dep_448'; did you mean 'dep_208'?
                dep_448 = dep_1118; /* vertex #0 */
                ^~~~~~~
                dep_208
How can I run it correctly? Thanks.
https://github.com/HexHive/FuzzGen/blob/master/examples/libopus/opus_decode_fuzzer-LLVMFuzzerTestOneInput%2Btest_opus_api-main%2Bopus_demo-main%2Bopus_encode_regressions-regression_test%2Brepacketizer_demo-main%2Btest_opus_encode-main%2Btest_opus_padding-main%2Btrivial_example-main/opus_decode_fuzzer-LLVMFuzzerTestOneInput%2Btest_opus_api-main%2Bopus_demo-main%2Bopus_encode_regressions-regression_test%2Brepacketizer_demo-main%2Btest_opus_encode-main%2Btest_opus_padding-main%2Btrivial_example-main_fuzzer.cpp
this is the driver i have tried.

**Comment by gannimo** [comment]
Hm, I think dep_448 should be dep_1118 for all instances (from the global list). @ispoleet should have a look :)

**Comment by frokaikan** [comment]
fuzzgen1.cpp:2006:34: error: use of undeclared identifier 'dep_450'; did you mean 'dep_453'?
                opus_decoder_ctl(dep_450, 4028); /* vertex #30 */
                                 ^~~~~~~
                                 dep_453

It seeds that there are not only one problem...... :(

**Comment by ispoleet** [comment]
Just declare dep_448 :) That's a bug, some variables are not declared properly.
