### ISSUE TITLE
TerminatorInst’ does not name a type

### ISSUE THREAD

**Issue by zhoulaifu** [HexHive/FuzzGen#13]
I got an error when compiling the tool on a Ubuntu 18 machine:

 ```
layout.cpp:350:15: error: ‘TerminatorInst’ does not name a type
         const TerminatorInst *ti = blk->getTerminator();

```

It occurred while 

`[ 58%] Building CXX object CMakeFiles/fuzzgen.dir/src/layout.cpp.o
`

Can you help?

**Comment by Marsman1996** [comment]
It might be due to the version of LLVM you use.
I use LLVM 7.0.0 and could compile the FuzzGen successfully.

**Comment by gannimo** [comment]
Yes, please use LLVM 6 or 7 (with slight changes). Some knowledge of LLVM is required to build FuzzGen.
Reopen if recompilation with an older version of LLVM does not work.

**Comment by zhoulaifu** [comment]
I was using LLVM 8, FYI.
```
$clang --version
clang version 8.0.0 (trunk 351050)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

$ llvm-config --version
8.0.0svn
```
