### ISSUE TITLE
fuzzgen-preprocessor arguments 

### ISSUE THREAD

**Issue by minhonoshin** [HexHive/FuzzGen#4]
Hi~~~

I have some questions~~
After build the 'fuzzgen-preprocesor' binary.

And then, I want to generate metadata file. But, it have some error, like below message

/llvm-objects/bin$ ./fuzzgen-preprocessor -outfile=opus.meta -library-root=~/opus-1.3.1/src/
[INFO] Starting FuzzGen Preprocessor v3.1 at 30-07-2020 17:01:02 PDT
[INFO] Please ignore the following errors (failure to load a compilation database)...
LLVM ERROR: CommonOptionsParser: failed to parse command-line arguments. [CommonOptionsParser]: fuzzgen-preprocessor: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: ./fuzzgen-preprocessor -help

**Comment by Marsman1996** [comment]
Well, I think it should be 
`./fuzzgen-preprocessor -outfile=opus.meta -library-root=~/opus-1.3.1/src/ A.c B.c C.c`

**Comment by minhonoshin** [comment]
it worked well~~ thanks.

**Comment by Marsman1996** [comment]
Do you run the FuzzGen to fuzz the library on Ubutnu?
I tried it on several libraries like libtiff, but it failed.

**Comment by minhonoshin** [comment]
Not yet..  n.n
i also tried several times. but it failed too.

**Comment by Marsman1996** [comment]
Well, thanks anyway
hope they will update the document with more details :(

**Comment by wqi1** [comment]
Could you please share your Ubuntu version and llvm/clang version ？I wonder if there are other requirement to build FuzzGen ，because I tried to compile the program with cmake -make process but met a lot of errors. Looking forward for your reply !

**Comment by Marsman1996** [comment]
@wqi1 I use Ubuntu 16.04 and LLVM 7.0.0, and you also need to install libboost.

**Comment by wqi1** [comment]
@Marsman1996 Thank u very much ! I built FuzzGen well . Then I followed the preprocessor building steps but it did not show up under $BUILD_LLVM_DIR/bin directory. Can you help me out ? Here were what I did :
1）copy the preprocessor directory under $LLVM_SRC/tools/clang/tools 
2）add "add_clang_subdirectory(fuzzgen)" in $LLVM_SRC/tools/clang/tools/CMakeLists.txt:
3）cd llvm/build
4)  cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../llvm-7.0.0.src
5)  make
6)  sudo make install
but the preprocessor did not show up under $BUILD_LLVM_DIR/bin directory.

**Comment by Marsman1996** [comment]
@wqi1 Well, do you rename the 'preprocessor' folder to 'fuzzgen' as https://github.com/HexHive/FuzzGen/pull/7 suggests?

**Comment by wqi1** [comment]
@Marsman1996 Thanks a lot！I renamed the directory and modified the cmake_cache . Do you know how to emit bitcode (*.bc) files with Android.bp on Ubuntu ? It seems the developers run this program on android environment.

**Comment by Marsman1996** [comment]
@wqi1 Well, I know little about Android and I also failed in this step. Sorry I can not help you about this.

**Comment by gannimo** [comment]
Due to the complexity, the abstraction and generalization code is somewhat brittle. It works best for Android AOSP but we've also got it to work with some Debian 9.0 libraries. Especially when moving to non-Android, some adjustments are expected.

Are there any questions left?
