### ISSUE TITLE
Does it work for Debian libraries too?

### ISSUE THREAD

**Issue by imanoracle** [HexHive/FuzzGen#5]
Thanks for sharing your awesome project. Does it work for Debian libraries too?

**Comment by gannimo** [comment]
We tried it on several Debian libraries in our evaluation. 
https://nebelwelt.net/files/20SEC.pdf section 6.4
As you've likely seen, this is research-quality code that requires some hand holding and very specific LLVM and system versions to compile (and likely a complete rewrite for production).
