### ISSUE TITLE
Compilation errors 

### ISSUE THREAD

**Issue by wcshim40** [HexHive/FuzzGen#6]
Thank you for your great work!
I would love to use FuzzGen to synthesize fuzzers but I got compilation errors. Can you take a look and help me to move further?

```
preprocessor.cpp:569:42: error: no matching function for call to
 ‘std::vector<std::__cxx11::basic_string<char> >::push_back(llvm::StringRef&)’
         incDeps[ mod ].push_back(FileName);
                                          ^
In file included from /usr/include/c++/8/vector:64,

/preprocessor.cpp:613:67: error: conversion from ‘llvm::SmallVector<clang::FrontendInputFile, 0>’
to non-scalar type ‘std::vector<clang::FrontendInputFile>’ requested
     vector<FrontendInputFile> Inputs = compInst.getFrontendOpts().Inputs;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

preprocessor.cpp:614:40: error: conversion from ‘llvm::StringRef’ 
to non-scalar type ‘std::__cxx11::string’ {aka ‘std::__cxx11::basic_string<char>’} requested
     string filename = Inputs[0].getFile();
                       ~~~~~~~~~~~~~~~~~^~
```

Here are the steps for the compilation.

1. Checkout LLVM: git clone https://github.com/llvm/llvm-project.git
2. Configure and build LLVM and Clang:
3. Move `src/preprocessor` to `llvm-project/clang-tools-extra/fuzzgen`
4. Add `add_subdirectory(fuzzgen)` to `llvm-project/clang-tools-extra/CMakeLists.txt`
5. Get compilation errors

Any comments or suggestions

**Comment by gannimo** [comment]
Can you try with LLVM 7.0 and Ubuntu 16.04 or Debian 9.0? Please open the issue again if it persists.
